development:
  adapter: postgresql
  encoding: unicode
  database: database_pokecoin_development
  pool: 5
  host: localhost
  username: postgres_user_name
  password: postgres_password

test:
  adapter: postgresql
  encoding: unicode
  database: database_pokecoin_test
  pool: 5
  username: postgres_user_name
  password: postgres_password

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 